In [53]:
import pandas as pd
salarydf = pd.read_csv("C:\\Users\\sveer\\Edureka\\Data Science\\Assignments\\Module 5\\Salaries.csv", dtype={12: str})
print (salarydf.info())

#1. How much salary cost has increased from the year 2011 to 2014
df2011 = salarydf.loc[salarydf["Year"] == 2011]
df2014 = salarydf.loc[salarydf["Year"] == 2014]
print ("Total salary in 2011", df2011["TotalPay"].sum())
print ("Total salary in 2014", df2014["TotalPay"].sum())
print ("Increased cost",df2014["TotalPay"].sum() - df2011["TotalPay"].sum())

#2. Which job title in the year 2014 has the highest mean salary?
meandf = df2014.groupby("JobTitle")["TotalPay"].mean()
meandf.sort_values(ascending=False,inplace=True)
print (meandf)
print ("highest mean job title",meandf.index[0])

#3. How much money could have been saved in the Year 2014 by stopping OverTimePay
print("Overtimepay for 2014",df2014["OvertimePay"].sum())

#4. Top 5 common jobs in 2014 and how much do they cost SFO
print ("Common jobs")
common_jobs = df2014['JobTitle'].value_counts().head(5)
top_jobs_df = df2014[df2014['JobTitle'].isin(common_jobs.index)]
total_salary_costs = top_jobs_df.groupby('JobTitle')['TotalPay'].sum()
total_salary_costs_formatted = total_salary_costs.apply(lambda x: "{:,.2f}".format(x))
print (total_salary_costs_formatted)

#5. Top earning employee across all years
salarydfsorted = salarydf.sort_values(by='TotalPay',ascending=False)
print ("Top earning employee",salarydfsorted.iloc[0])

#e2. In year 2011 OverTimePay was what percentage of  TotalPayBenefits
totalpay2011 = df2011["TotalPayBenefits"].sum()
overtimepay2011 = df2011["OvertimePay"].sum()
print ("TotalPayBenefits pay was over by ", (overtimepay2011/totalpay2011)*100)

#e3. Which Job Title in the Year 2014 has the lowest mean salary
salarymean = df2014.groupby("JobTitle")["TotalPayBenefits"].mean()
sortedsal = salarymean.sort_values(ascending=True)

# The job title with the lowest mean salary
lowest_salary_job = sortedsal.index[0]
lowest_salary_value = sortedsal.iloc[0]

print(f"The job title with the lowest mean salary in 2014 is '{lowest_salary_job}' with a mean salary of {lowest_salary_value:.2f}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148648 entries, 0 to 148647
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148648 non-null  int64
 1   EmployeeName      148648 non-null  object
 2   JobTitle          148648 non-null  object
 3   BasePay           148043 non-null  float64
 4   OvertimePay       148648 non-null  float64
 5   OtherPay          148648 non-null  float64
 6   Benefits          112490 non-null  float64
 7   TotalPay          148648 non-null  float64
 8   TotalPayBenefits  148648 non-null  float64
 9   Year              148648 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148648 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(7), int64(2), object(4)
memory usage: 14.7+ MB
None
Total salary in 2011 2594113030.72
Total salary in 2014 2876910951.2599998
Increased cost 282797920.53999996
JobTitle
Chief Investment Officer       339653.700000
Chief of Police                326716.760000
Chief, Fire Department         326233.440000
Gen Mgr, Public Trnsp Dept     294000.180000
Dep Chf of Dept (Fire Dept)    285575.785000
                                   ...
BdComm Mbr, Grp5,M$100/Mo        1300.115926
Special Examiner                 1141.172414
BdComm Mbr, Grp3,M=$50/Mtg        691.904762
BdComm Mbr, Grp2,M=$25/Mtg        325.000000
Special Assistant 15                0.000000
Name: TotalPay, Length: 996, dtype: float64
highest mean job title Chief Investment Officer
Overtimepay for 2014 205918599.26999998
Common jobs
JobTitle
Firefighter                     113,283,574.60
Public Svc Aide-Public Works      8,535,453.79
Registered Nurse                144,406,501.26
Special Nurse                    49,498,738.23
Transit Operator                152,007,977.75
Name: TotalPay, dtype: object
Top earning employee Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object
TotalPayBenefits pay was over by  6.31503365427881
The job title with the lowest mean salary in 2014 is 'BdComm Mbr, Grp2,M=$25/Mtg' with a mean salary of 345.42